const Link = require('./index');

var link = new Link();
link.append('我是第一个');
link.append('22222222');
link.append('33333333');
link.append('44444444');
link.append('55555555');
link.append('66666666');
link.print();
console.log('----------------');
link.insert(2, '我插入在333后面哦');
link.print();
console.log('----------------');
link.remove(3);
link.print();
console.log('----------------');
link.remove_head();
link.print();
console.log('----------------');
link.remove_tail();
link.print();
console.log('----------------');
console.log('indexOf', link.indexOf('44444444'));
link.print();
console.log('----------------');
console.log('get', link.get(2));
link.print();
console.log('----------------');
console.log('head', link.head());
link.print();
console.log('----------------');
console.log('tail', link.tail());
link.print();
console.log('----------------');
console.log('length', link.length());
link.print();
console.log('----------------');
console.log('isEmpty', link.isEmpty());
link.print();
console.log('----------------');
console.log('clear', link.clear());
link.print();
console.log('----------------');
